plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

version = mod_version
group = mod_group_id
base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            arg '-mixin.config=moremnaglyphuses.mixins.json'
            mods { "${mod_id}" { source sourceSets.main } }
        }
        client { args '--username', 'Huto' }
        server { args '--nogui' }
    }
}

mixin {
    add sourceSets.main, 'moremnaglyphuses.refmap.json'
    config 'moremnaglyphuses.mixins.json'
}

repositories {
    maven { url = 'https://www.cursemaven.com' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation fg.deobf('curse.maven:geckolib-388172:5460312')
    implementation fg.deobf('curse.maven:curios-309927:5066845')
    implementation fg.deobf('curse.maven:mana-and-artifice-406360:6847805')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

test { useJUnitPlatform() }

tasks.named('processResources', ProcessResources).configure {
    def props = [minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
                 forge_version: forge_version, forge_version_range: forge_version_range,
                 loader_version_range: loader_version_range, mod_id: mod_id, mod_name: mod_name,
                 mod_license: mod_license, mod_version: mod_version, mod_authors: mod_authors,
                 mod_description: mod_description]
    inputs.properties props
    filesMatching(['META-INF/mods.toml']) { expand props }
}

tasks.named('jar', Jar).configure {
    manifest.attributes('MixinConfigs': 'moremnaglyphuses.mixins.json')
    finalizedBy 'reobfJar'
}
